### ISSUE TITLE
Great theme - some suggestions

### ISSUE THREAD

**Issue by nickpoison** [pages-themes/hacker#123]
This is a great theme and I have only 2 suggestions.  (I'm editing this to get everything in one comment.)

+ First, and I think this applies to all supported themes, is there is no support for math.  For those interested, in _layouts/default.html,  I added the following after `{% include head-custom.html %}`:
```css
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: {
    fontCache: 'global'
  }
};
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>

<link href='https://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet'>
```
This works fine, but I'm not sure why something like this isn't incorporated in these themes.  The 'link' is for using google fonts... see the next item.

+ Second, text font should _not_ be mono.  It makes reading text difficult, and it started giving me a headache.   I added  _assets_css/style.scss as follows.  The first changes the 'p' tag to be sans-serif  and the second changes the 'code' tag to be "Inconsolata", which is a google font. 

```css
---
---

@import "{{ site.theme }}";
 p  *
{
   font-family: Verdana, Arial, sans-serif !important;
}

code *
{
   font-family: 'Inconsolata', Monaco, "Bitstream Vera Sans Mono", "Lucida Console", Terminal, monospace !important;
}
```
It's so much easier to read the text now.  

Thanks for a great theme.

**Comment by nickpoison** [comment]
Oh sorry, I should have expanded on the  2nd and 3rd points.  After changing the `body` font, the `<code>` font was also changed.   So in  `_assets_css/style.scss`  I have another line:

```css
---
---

@import "{{ site.theme }}";
 body *
{
   font-family: Verdana, Arial, sans-serif !important;
}

code *
{
   font-family: 'Inconsolata', Monaco, "Bitstream Vera Sans Mono", "Lucida Console", Terminal, monospace !important;
}
```

and to `_layouts/default.html` I added:
```css
<link href='https://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet'>
```
which is there only because I added a google font
