### ISSUE TITLE
Hacker theme does not print well

### ISSUE THREAD

**Issue by bovlb** [pages-themes/hacker#148]
I use hacker for my website, but I found it doesn't print well.  This is important to me, as my website is intended to double as handouts.  Here are a few suggested changes for `style.css`.

`text-shadow` properties seem to make my printing (from Google Chrome) take a long time to preview, and make my printer fail the job.  Wrapping some of these in `@media screen { ... }` I resolved the problem.

For me, the screen text is perfect, but the printed text comes out a little too large.  This is pretty clumsy, but I'm happy with 

```css
@media print
{
    * { font-size: 90%; }
}
```

The dark mode works great on screen, but for print the text comes out a little light without the background.

I found that code samples were being truncated (at less than 80 columns) which makes them a bit useless, so I added:
```css
pre {
    white-space: pre-wrap;
    break-inside: avoid;
    border: thin solid #666666;
}
```
