### ISSUE TITLE
Cropped Title on mobile

### ISSUE THREAD

**Issue by fornellas** [pages-themes/hacker#19]
My page https://fornellas.github.io/3d_printed_keyboard/ when opened from Chrome on a Galaxy S7 is rendered like this:

https://photos.app.goo.gl/Wunaa4Li2m1zLKoP2

Everything renders OK, but the green title gets its left side cropped.

**Comment by fornellas** [comment]
https://github.com/fornellas/3d_printed_keyboard/commit/14eee647e1518510ae03d8bdb1fc70042c487ad3
This fixed the issue for me.

**Comment by karussell** [comment]
This is still not fixed. The fix from @fornellas does it:

```scss
---
---

@import "{{ site.theme }}";

header h1 {
  margin: 0 0 0 0;
} 
```

BTW: Thanks for this theme!
