### ISSUE TITLE
issue with ul li in CSS

### ISSUE THREAD

**Issue by ousia** [pages-themes/hacker#2]
Would it be possible that the following CSS code:

``` css
ul li {
  list-style: none;
}

ul li:before {
  content: ">>";
  font-family: Monaco, "Bitstream Vera Sans Mono", "Lucida Console", Terminal, monospace;
  font-size: 13px;
  color: #b5e853;
  margin-left: -37px;
  margin-right: 21px;
  line-height: 16px;
}
```

coud be replaced with something similar to the following snippet borrowerd from the leap-day theme?

``` css
ul{
  list-style-image:url('../images/bullet.png');
}
```

Sorry, but otherwise Firefox gets broken list items (such as described in jasoncostello/slate#9).

Using the CSS code above, I’m afraid that a block element shouldn’t have any element on its left (remember that `<li>` may contain `<p>`).

A simple way to fix the issue would be to use an image (such as described above).

Could you fix this? (Sorry, but I’m afraid that customizing CSS won’t work here after importing.)

Many thanks for your help.

**Comment by benbalter** [comment]
@ousia Can you submit some screenshots of what you're describing?

**Comment by ousia** [comment]
@benbalter, here you have the list item from the _Hacker_ theme:

![lists-hacker](https://cloud.githubusercontent.com/assets/203767/21326004/28de7ede-c629-11e6-9a40-4167042fb266.png)

List item markers are on a different paragraph from the list items themselves.

The _Leap Day_ theme displays markers and list items on the same paragraph:

![lists-leap-day](https://cloud.githubusercontent.com/assets/203767/21326003/28ce36aa-c629-11e6-9dc7-667bc948de2d.png)

Would it be possible that the _Hacker_ theme uses images for lists markers as shown above?

Many thanks for your help.

**Comment by ousia** [comment]
@benbalter, after the key to #4, I guess a temporary fix might read:

``` css
ul li {
  list-style: disc;
}

ul li:before {
    content: none
}
```

Would you be interested in a PR with those contents?
