### ISSUE TITLE
Proper way to override task-list display

### ISSUE THREAD

**Issue by jimhall** [pages-themes/hacker#75]
Issue: when creating an task list item like so in a post:

```md
- [x] Review relevant GitHub Labs
```
It generates the following display:

![image](https://user-images.githubusercontent.com/7142231/126001302-35ea0005-6b4e-42e7-9b49-a6b423712aeb.png)

I would like to eliminate the green '>>' prior to the check area. I think it is redundant.
My challenge is that I don't know where I can change this behavior.

Does anyone know how to eliminate the green '>>'?

Workaround: I created a black dot to hide the green '>>'

I created an inline style for the post.html file using directions from [this link](https://www.w3schools.com/howto/howto_css_bullet_color.asp):

```css
<style>
ul.task-list {
  list-style: none; /* Remove default bullets */
}
ul.task-list li::before {
  content: "\2022";  /* Add content: \2022 is the CSS Code/unicode for a bullet */
  color: #151515; /* Change the color */
  font-weight: bold; /* If you want it to be bold */
  display: inline-block; /* Needed to add space between the bullet and the text */
  width: 1em; /* Also needed for space (tweak if needed) */
  margin-left: -3.5em; /* Also needed for space (tweak if needed) */
}
li.task-list-item {
  list-style-image: url("{{ '/assets/images/black-dot.png' | relative_url }}");
}
</style>
```

**Comment by davorpa** [comment]
Hi @jimhall

Here is where it is defined:

https://github.com/pages-themes/hacker/blob/4c942506cf8d5329a9cbc66b1eff75ad86a49e34/_sass/jekyll-theme-hacker.scss#L152-L154

Try to put this rule above:

```css
ul.task-list {
    list-style: none;
}
ul li.task-list-item {
    list-style-image: none;
}
```

Even easier, it isnt?

For a complete implementation acording this theme guidelines see PR #83
